export const defaultValues = {
    _1REG_ANS: '330281',
    _3GUIA_SOLIC_INT: undefined,
    _2GN_GUIA_PREST: undefined,
    _4DT_DE_AUT: undefined,
    _5SENHA_GUI_RES_INT: undefined,
    _6VAL_DE_SENHA: undefined,
    _7N_GUIA_OP: undefined,
    // Section 1
    _8NUM_CART: undefined,
    _9VAL_CART: undefined,
    _10NOME_BENEF: undefined,
    _11CART_NAC_SAUD: undefined,
    _12AT_A_RN: false,
    // Section 2
    _13COD_OP_CNPJ: '09306242000344',
    _14NOME_CONT: undefined,
    _15COD_CNES: '7730802',
    // Section 3
    _16CAR_INT: undefined,
    _17TIPO_FAT: 4,
    _18HORA_INIC_FAT: undefined,
    _18DATA_INIC_FAT: undefined,
    _20HORA_FIM_FAT: undefined,
    _20DATA_FIM_FAT: undefined,
    _22TIPO_INT: undefined,
    _23REGIME_INT: undefined,
    _24CID_101: undefined,
    _25CID_102: undefined,
    _26CID_103: undefined,
    _27CID_104: undefined,
    _28IND_DE_ACID: 9,
    _29MOTIV_DE_ENCER: 11,
    // Section 4
    _30TIPO_DE_DECL: 1,
    _31CID_OBITO: undefined,
    _32NUMERO_DECL: undefined,
    _33OBITO_RN: false,
    // Section 5
    _34DATA_PROC: undefined,
    _35HORA_INICIO_PROC: undefined,
    _36HORA_FIM_PROC: undefined,
    _37TAB_PROC: undefined,
    _38COD_PROC: undefined,
    _39DESC_PROC: undefined,
    _40QTD_PROC: undefined,
    _41VIA_PROC: 'Unica',
    _42TEC_PROC: 'Convencional',
    _43RED_ACRESC: undefined,
    _44VALOR_UNIT_PROC: undefined,
    _45VALOR_TOT_PROC: '14,00',
    // Section 6
    _46SEQ_REF: undefined,
    _47GRAU_PART: 0,
    _48COD_OP_CPF: undefined,
    _49NOME_PROF_EQUIP: undefined,
    _50NOME_CONS_PROF_EQUIP: undefined,
    _51NUM_CONSELHO_EQUIP: undefined,
    _52UF_EQUIP: undefined,
    _53COD_CBO_EQUIP: undefined,
    // Section 7
    _54TOTAL_PROCED: 'Teste',
    _55TOTAL_DIAR: 'Teste',
    _56TOTAL_TAXAS_ALUG: 'Teste',
    _57TOTAL_MAT: 'Teste',
    _58TOTAL_OPME: 'Teste',
    _59TOTAL_MEDC: 'Teste',
    _60TOTAL_GASES: 'Teste',
    _61TOTAL: 'Teste',
    _81OBS_TOTAL: undefined,
    // Section 8
    _106CD_REALIZADA: 1,
    _107DATA_DESP: undefined,
    _108HORA_INICIO_DESP: undefined,
    _109HORA_FIM_DESP: undefined,
    _110TAB_DESP: undefined,
    _111ITEM_DESP: undefined,
    _112QTD_DESP: undefined,
    _UNID_MEDIDA: undefined,
    _113RED_ACRESC_DESP: undefined,
    _114VALOR_UNIT_DESP: undefined,
    _115TOTAL: 'Valor Total',
    _116DESCR: undefined,
    _REG_ANVISA: undefined,
    _REF_FABRIC: undefined,
    _AUT_FUNC: undefined,
    //Section 9
    _117TOTAL_GASES: 'teste',
    _118TOTAL_MEDC: 'teste',
    _119TOTAL_MAT: 'teste',
    _120TOTAL_TAXAS_ALUG: 'teste',
    _121TOTAL_DIAR: 'teste',
    _122TOTAL_OPME: 'teste',
    _123TOTAL: 'teste'
}