export const _1REG_ANS = 'regANS'
export const _3GUIA_SOLIC_INT = 'guiaSolictInt'
export const _2GN_GUIA_PREST = 'gnGuiaPrest'
export const _4DT_DE_AUT = 'dtDeAut'
export const _5SENHA_GUI_RES_INT = 'senhaGuiResInt'
export const _6VAL_DE_SENHA = 'valDeSenha'
export const _7N_GUIA_OP = 'nGuiaOp'
// Section 1
export const _8NUM_CART = 'numCart'
export const _9VAL_CART = 'valCart'
export const _10NOME_BENEF = 'nomeBenef'
export const _11CART_NAC_SAUD = 'cartNacSaud'
export const _12AT_A_RN = 'atARN'
// Section 2
export const _13COD_OP_CNPJ = 'codOpCNPJ'
export const _14NOME_CONT = 'nomeCont'
export const _15COD_CNES = 'codCNES'